# Generated by Django 4.2.30 on 2026-07-31 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('name', models.CharField(blank=True, max_length=120, verbose_name='Имя')),
                ('source', models.CharField(blank=True, default='landing', max_length=64, verbose_name='Источник')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contacted', models.BooleanField(default=False, verbose_name='Связались')),
                ('notes_admin', models.TextField(blank=True, verbose_name='Заметки админа')),
            ],
            options={
                'verbose_name': 'Заявка waitlist',
                'verbose_name_plural': 'Waitlist',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=120, verbose_name='Имя')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('birth_time', models.TimeField(blank=True, null=True, verbose_name='Время рождения')),
                ('birth_place', models.CharField(blank=True, max_length=255, verbose_name='Место рождения')),
                ('timezone', models.CharField(blank=True, default='UTC', max_length=64, verbose_name='Часовой пояс')),
                ('onboarding_completed', models.BooleanField(default=False, verbose_name='Онбординг пройден')),
                ('notes_admin', models.TextField(blank=True, verbose_name='Заметки админа')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('mood', models.CharField(blank=True, choices=[('low', 'Низкое'), ('mixed', 'Смешанное'), ('ok', 'Нормально'), ('high', 'Высокое')], max_length=16, verbose_name='Настроение')),
                ('energy', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Энергия 1–10')),
                ('body', models.TextField(blank=True, verbose_name='Запись')),
                ('tags', models.CharField(blank=True, help_text='через запятую', max_length=255, verbose_name='Теги')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Запись дневника',
                'verbose_name_plural': 'Дневник',
                'ordering': ['-date', '-created_at'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
