# Generated by Django 4.2.30 on 2026-07-31 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalPlanetaryCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=64, unique=True, verbose_name='Ключ')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cycle_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Планетарный цикл',
                'verbose_name_plural': 'Планетарные циклы',
                'ordering': ['-starts_at', 'key'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True, verbose_name='URL slug')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Подзаголовок')),
                ('step_type', models.CharField(choices=[('content', 'Контент / экран'), ('birth_data', 'Данные рождения'), ('waitlist', 'Контакты waitlist'), ('input', 'Ввод пользователя'), ('custom', 'Кастомный')], default='custom', max_length=32, verbose_name='Тип шага')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_required', models.BooleanField(default=True, verbose_name='Обязательный')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('fields_schema', models.JSONField(blank=True, default=dict, verbose_name='Схема полей')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='Мета')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Шаг онбординга',
                'verbose_name_plural': 'Шаги онбординга',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='birth_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='profile',
            name='birth_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='profile',
            name='registration_status',
            field=models.CharField(choices=[('waitlist', 'Waitlist'), ('pending', 'Ожидает регистрации'), ('active', 'Зарегистрирован')], default='waitlist', max_length=16, verbose_name='Статус регистрации'),
        ),
        migrations.AddField(
            model_name='profile',
            name='telegram',
            field=models.CharField(blank=True, max_length=64, verbose_name='Telegram'),
        ),
        migrations.AddField(
            model_name='waitlistlead',
            name='converted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Конвертирован в пользователя'),
        ),
        migrations.AddField(
            model_name='waitlistlead',
            name='phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='waitlistlead',
            name='telegram',
            field=models.CharField(blank=True, max_length=64, verbose_name='Telegram'),
        ),
        migrations.AddField(
            model_name='waitlistlead',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waitlist_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='OnboardingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('in_progress', 'В процессе'), ('completed', 'Завершён'), ('converted', 'Конвертирован в аккаунт')], default='in_progress', max_length=16)),
                ('current_step_slug', models.SlugField(blank=True, max_length=64, verbose_name='Текущий шаг')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('birth_time', models.TimeField(blank=True, null=True)),
                ('birth_place', models.CharField(blank=True, max_length=255)),
                ('birth_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('birth_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('timezone', models.CharField(blank=True, default='UTC', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_sessions', to=settings.AUTH_USER_MODEL)),
                ('waitlist_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_sessions', to='core.waitlistlead')),
            ],
            options={
                'verbose_name': 'Сессия онбординга',
                'verbose_name_plural': 'Сессии онбординга',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NatalChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField()),
                ('birth_time', models.TimeField(blank=True, null=True)),
                ('birth_place', models.CharField(blank=True, max_length=255)),
                ('birth_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('birth_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('timezone', models.CharField(blank=True, default='UTC', max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Ожидает расчёта'), ('ready', 'Готово'), ('failed', 'Ошибка')], default='pending', max_length=16)),
                ('chart_data', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('calculated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='natal_chart', to='core.onboardingsession')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='natal_charts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Натальная карта',
                'verbose_name_plural': 'Натальные карты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=128, verbose_name='Ключ')),
                ('source', models.CharField(choices=[('onboarding', 'Онбординг'), ('product', 'Продукт'), ('security', 'Вопрос безопасности'), ('other', 'Другое')], default='product', max_length=32)),
                ('value', models.JSONField(default=dict, verbose_name='Значение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inputs', to='core.onboardingsession')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ввод пользователя',
                'verbose_name_plural': 'Вводы пользователей',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'key'], name='core_userin_user_id_50cf51_idx'), models.Index(fields=['session', 'key'], name='core_userin_session_c21e0c_idx')],
            },
        ),
        migrations.CreateModel(
            name='OnboardingStepAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField(default=dict, verbose_name='Данные шага')),
                ('completed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.onboardingsession')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='core.onboardingstep')),
            ],
            options={
                'verbose_name': 'Ответ шага онбординга',
                'verbose_name_plural': 'Ответы шагов онбординга',
                'ordering': ['step__order', 'id'],
                'unique_together': {('session', 'step')},
            },
        ),
    ]
