# Generated by Django 4.2.30 on 2026-08-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_globalplanetarycycle_onboardingstep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitlistlead',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email'),
        ),
    ]
