# Generated by Django 4.2.30 on 2026-08-14 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0003_waitlist_email_optional"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                (
                    "idempotency_key",
                    models.CharField(db_index=True, max_length=128, unique=True, verbose_name="Ключ идемпотентности"),
                ),
                (
                    "idempotency_request_hash",
                    models.CharField(
                        help_text="SHA-256 канонического тела (сессия + sku). Повтор с другим телом → 409.",
                        max_length=64,
                        verbose_name="Хэш запроса идемпотентности",
                    ),
                ),
                ("customer_email", models.EmailField(blank=True, max_length=254, verbose_name="Email")),
                ("customer_phone", models.CharField(blank=True, max_length=32, verbose_name="Телефон")),
                ("customer_telegram", models.CharField(blank=True, max_length=64, verbose_name="Telegram")),
                ("product_sku", models.SlugField(max_length=64, verbose_name="SKU")),
                ("product_name", models.CharField(max_length=255, verbose_name="Товар")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Сумма")),
                ("currency", models.CharField(default="rub", max_length=8, verbose_name="Валюта")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Создаётся"),
                            ("awaiting_payment", "Ожидает оплаты"),
                            ("paid", "Оплачен"),
                            ("canceled", "Отменён"),
                            ("denied", "Отклонён"),
                            ("failed", "Ошибка"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=24,
                    ),
                ),
                ("payment_url", models.URLField(blank=True, max_length=500, verbose_name="Ссылка на оплату")),
                (
                    "prodamus_order_id",
                    models.CharField(blank=True, db_index=True, max_length=64, verbose_name="ID заказа в Prodamus"),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True, verbose_name="Оплачен")),
                ("webhook_payload", models.JSONField(blank=True, default=dict, verbose_name="Последний webhook")),
                ("last_error", models.TextField(blank=True, verbose_name="Последняя ошибка")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="core.onboardingsession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "waitlist_lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="core.waitlistlead",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["session", "product_sku", "status"], name="core_order_session_d4e8a7_idx"),
        ),
    ]
