# Generated by Django 4.2.30 on 2026-09-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_chartshare'),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportsectionfeedback",
            name="comment_skipped",
            field=models.BooleanField(default=False, verbose_name="Отправлено без комментария"),
        ),
        migrations.AlterField(
            model_name="reportsectionfeedback",
            name="rating",
            field=models.CharField(
                choices=[
                    ("about_me", "🌝 Про меня"),
                    ("partial", "🌗 Частично"),
                    ("not_about_me", "🌚 Не про меня"),
                ],
                max_length=16,
                verbose_name="Оценка",
            ),
        ),
    ]
